# Dockerfile
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the requirements to the container
COPY requirements.txt /app/

# Install the required dependencies
RUN pip install --no-cache-dir -r requirements.txt
